---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install required software
  apt: name={{ item }} state=present
  with_items:
    - apache2
    - mariadb-server
    - php-mysql
    - php
    - libapache2-mod-php
    - php-mcrypt
    - python-mysqldb
