Vagrant.configure("2") do |config|

  config.vm.define "s-adm" do |sadm|
    sadm.vm.box = "bento/debian-10.7"
    sadm.vm.hostname = 's-adm'
   sadm.vm.network :public_network, ip: "dhcp"
   sadm.vm.network :private_network, ip: "192.168.99.99", mask: "24"

    config.vm.provider :virtualbox do |v|
      v.memory = 512
#      v.cpus = 2
    end
  end

  config.vm.define "s-infra" do |v|
    v.vm.box = "bento/debian-10.7"
    v.vm.hostname = 's-infra'
    v.vm.network :private_network, ip: "192.168.99.1", mask: "24"
    v.vm.network :private_network, ip: "172.16.0.1", mask: "24"
  end
end

