---
# tasks file for mariadb
- name: Installation de python-mysqldb
  apt: name=python-mysqldb state=present

- name: Installation de mariadb-server
  apt: name=mariadb-server state=present

- name: Create mysql database
  mysql_db: name={{ maria_dbname }} state=present

- name: Commenter la ligne
  replace: dest=/etc/mysql/mariadb.conf.d/50-server.cnf
             regexp='bind-address		= 127.0.0.1'
             replace='#bind-address            = 127.0.0.1'