---
# - name: Create mysql database
#   mysql_db: name={{ wp_mysql_db }} state=present

# - name: Create mysql user
#   mysql_user: 
#     name={{ wp_mysql_user }} 
#     password={{ wp_mysql_password }} 
#     priv=*.*:ALL
#     host=localhost

 - name: copy .my.cnf file with root password credentials
   copy: src=.my.cnf dest=/root/.my.cnf owner=root mode=0600
