---
- name: installation des paquets web
  apt:
    name:
      - apache2
      - php
      - php-mbstring
      - php-mysql
      - mariadb-client
    state: present

- name: install nfs-common
  apt:
    name: nfs-common
    state: present
