#!/bin/bash
if [[ $# != 1 ]] ; then
	echo "$0 - renomme une VM"  
	echo "usage : $0 <nouveaunom> "
	exit 1
fi
if [[ $1 == "version" ]] ; then
	echo 'chname v1.1 pour debian 11'
	exit 0
fi
oldname=$(hostname)
sed -i "s/${oldname}/$1/g" /etc/host{s,name}
echo 'redemarrer pour finaliser le changement du nom'
exit 0
