#!/bin/bash
apt-get  update
#upgrade -y
mkdir -p /root/tools/ansible
cd /root/tools/ansible
git clone https://gitea.lyc-lecastel.fr/gadmin/gsb2023.git
cd gsb2023/pre
export DEPL=192.168.99.99
bash gsbboot
cd ../..
bash pull-config
