---
#Installation ipsec strongswan côté gauche pour la communication via certificat
  - name: 1. install strongswan, com via certificat
    apt: name=strongswan state=present

  - name: install tcpdump
    apt: name=tcpdump state=present update_cache=yes

  - name: activation du routage
    copy: src=sysctl.conf dest=/etc/sysctl.conf

  - name: Copie fichier ipsec.conf
    copy: src=ipsec.conf dest=/etc/ipsec.conf
    notify: restart ipsec

  - name: Copie fichier ipsec.secrets
    copy: src=ipsec.secrets dest=/etc/ipsec.secrets
    notify: restart ipsec

  - name: Message d'information
    debug: msg="Veuillez consulter le document "r-vp.txt" dans ansible/gsb/doc"